# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2e2828d9b99ab1fa561a257c545e7a90bf10d83bb5c067d95d2167e385364693fe8809608c7946c79d5401937a06b9685c33607eb3ad5b8d8478a945392bb9e

test:
  secret_key_base: 3dd37b2ce9fb68189c7716ce38b7f47c6e8997708a0aa9fb209b89f50e9a22c9a7566691bdf52c828fb444a59dba5494f742c2af5476bcd260f39eebe9d91a77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
